
# configuration
RESULT_PATH = 'data'
ALLOWED_EXTENSIONS = set(['pdf'])
DEBUG = False

# Amazon S3 configuration
AWS_S3_ENABLED = False
ACCESS_KEY_ID = 'XXXXXXXXXXXXXXXXXXXX'
SECRET_ACCESS_KEY = 'XXXXXXXXXXXXXXXXXXX'